name: langton_ant
description: "Fourmi de Langton"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  injectable: ^2.5.2
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  retrofit: ^4.8.0
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio_mocked_responses: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  bdd_widget_test: ^2.1.2
  injectable_generator: ^2.9.0
  retrofit_generator: ^10.1.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/
